import streamlit as st
from rdkit import Chem
from rdkit.Chem import AllChem
import pubchempy as pcp
import os

st.set_page_config(page_title="Gaussian gjf生成工具", layout="centered")

st.title("🧪 分子 → Gaussian gjf 自动生成工具")

# ========= 输入区域 =========
uploaded_file = st.file_uploader("📷 上传二维结构图（可选）", type=["png", "jpg", "jpeg"])

name = st.text_input("🧾 化学名称（中文或英文）")
formula = st.text_input("🧪 分子式（可选）")
smiles = st.text_input("🔗 SMILES（推荐填写，最准确）")

polymer_n = st.number_input("🔁 聚合物链长 n（默认1）", min_value=1, value=1)

# ========= 生成按钮 =========
if st.button("🚀 生成 gjf 文件"):

    mol = None

    # ---------- 优先使用 SMILES ----------
    if smiles:
        mol = Chem.MolFromSmiles(smiles)
        st.info("使用 SMILES 构建分子")

    # ---------- 用名称查 ----------
    elif name:
        try:
            compounds = pcp.get_compounds(name, 'name')
            if compounds:
                smiles = compounds[0].isomeric_smiles
                mol = Chem.MolFromSmiles(smiles)
                st.info(f"通过名称获取 SMILES: {smiles}")
        except:
            st.error("名称解析失败")

    if mol is None:
        st.error("❌ 无法生成分子，请填写 SMILES 或正确名称")
        st.stop()

    # ---------- 聚合物处理 ----------
    mol = Chem.AddHs(mol)

    if polymer_n > 1:
        st.warning("⚠️ 聚合物采用重复拼接（简化模型）")
        base = mol
        for _ in range(polymer_n - 1):
            base = Chem.CombineMols(base, mol)
        mol = base

    # ---------- 生成3D ----------
    try:
        AllChem.EmbedMolecule(mol)
        AllChem.UFFOptimizeMolecule(mol)
        st.success("✅ 3D结构生成成功")
    except:
        st.warning("⚠️ 3D优化失败，但仍生成gjf")

    # ---------- 生成 gjf ----------
    gjf_content = "%chk=xzh.chk\n%mem=3GB\n%nprocshared=4\n"
    gjf_content += "# opt freq B3LYP/6-31G(d)\n\n"
    gjf_content += "Generated by Streamlit\n\n0 1\n"

    conf = mol.GetConformer()
    for i, atom in enumerate(mol.GetAtoms()):
        pos = conf.GetAtomPosition(i)
        gjf_content += f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n"

    gjf_content += "\n"

    # ---------- 下载 ----------
    st.download_button(
        label="📥 下载 gjf 文件",
        data=gjf_content,
        file_name="xzh.gjf",
        mime="text/plain"
    )